# Generated by Django 5.2.9 on 2025-12-10 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temp_2pm_7day', models.FloatField()),
                ('avg_pm25_7day', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='travel.district')),
            ],
        ),
    ]
